# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - testlaravelapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: testlaravelappacr.azurecr.io
  IMAGE_NAME: testlaravelapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E39CDBBCB5D6460184FE9CFE1406C0B8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_371DDDF8BD9D440B97BA97CB94C4EB94 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8776BF98EC9B4D119E5DFCD120563713 }}

      - name: Log in to the container registry
        run: az acr login --name ${{ env.REGISTRY }}

      - name: Build and push image
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name testlaravelapp \
            --resource-group testlaravelapp_group \
            --container-image-name "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" \
            --container-registry-url "https://${{ env.REGISTRY }}"
          az webapp restart --name testlaravelapp --resource-group testlaravelapp_group
